name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  buildr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build buildr and publish to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mangothecat/${{ github.job }}
        path: ./${{ github.job }}
        tag_with_ref: true
        push: true

  buildr-tidyverse:
    runs-on: ubuntu-latest
    needs: buildr
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build buildr-tidyverse and publish to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mangothecat/${{ github.job }}
        path: ./${{ github.job }}
        tag_with_ref: true
        push: true

  buildr-reticulate:
    runs-on: ubuntu-latest
    needs: buildr-tidyverse
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build buildr-reticulate and publish to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mangothecat/${{ github.job }}
        path: ./${{ github.job }}
        tag_with_ref: true
        push: true
  
  buildr-rmd:
    runs-on: ubuntu-latest
    needs: buildr-reticulate
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build buildr-rmd and publish to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mangothecat/${{ github.job }}
        path: ./${{ github.job }}
        tag_with_ref: true
        push: true
